server.port=${SERVER_PORT}
spring.application.name=${SPRING_APPLICATION_NAME}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED}
spring.h2.console.path=${SPRING_H2_CONSOLE_PATH}

spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}

dpi.queue-size=${DPI_QUEUE_SIZE}
dpi.num-load-balancers=${DPI_NUM_LOAD_BALANCERS}
dpi.fps-per-lb=${DPI_FPS_PER_LB}
dpi.connection-timeout-seconds=${DPI_CONNECTION_TIMEOUT_SECONDS}

jwt.secretKey=fajfkajdfi8f3h4ifenfjwjnj223j2jk3j920dmffd#sdfndsfnjdfjnjsdf@$@REWfdsfksdjfjdkfdhsfk
